name: Generate latest.json

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"   # run daily at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Find latest file
        id: latest
        run: |
          cd assets/newsletter/activity/2025
          # sort by name, which works here since names = dates
          LATEST=$(ls -1 *.json | sort | tail -1)
          echo "latest=$LATEST" >> $GITHUB_ENV

      - name: Copy to latest.json
        run: |
          cd assets/newsletter/activity/2025
          cp ${{ env.latest }} latest.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/newsletter/activity/2025/latest.json
          git commit -m "Update latest.json → ${{ env.latest }}" || echo "No changes"
          git push
